### ISSUE TITLE
Need compilation example for deployment as a static js file over php

### ISSUE THREAD

**Issue by didlie** [pldubouilh/live-torrent#10]
Need compilation example for deployment as a static js file over php. I was not able to use webpack compiled version of build.js with local copy of hls.js included as script tags in a static html page. Please create a version of this software that does not require a node server. I cannot contribute to this repository if I am forced to dedicate excessive hours to sifting the tree of node-loaded js files. Please make a simple, readable file from all these dependencies that can be included in html as a single script.

**Comment by pldubouilh** [comment]
#8
