### ISSUE TITLE
Browser-only implementation

### ISSUE THREAD

**Issue by didlie** [pldubouilh/live-torrent#16]
Looks great for clients who want to put Node on their desktop. What about browser-only/P2P-only capability. Forgive me if I'm wrong, but hte whole point is to run this P2P from client-browser-2-client-browser broadcasting video/audio. 

Maybe you are interested in adapting this to my website: didlie.com

My server-side is PHP and is really complicated:
https://github.com/didlie/WEBRTC_PHP_MIRROR_SERVER

**Comment by pldubouilh** [comment]
Sorry not really of interest !
