### ISSUE TITLE
Uncaught TypeError: Cannot read property 'register' of undefined

### ISSUE THREAD

**Issue by okgame** [pldubouilh/live-torrent#19]
Hello
Some time i got it error, some time not. But error much more (90%)
![image](https://user-images.githubusercontent.com/22207363/49743022-64d4dd80-fccc-11e8-9fb6-ce77a64f75ae.png)
When i got it error. Browser not load tracker.
![image](https://user-images.githubusercontent.com/22207363/49743065-803fe880-fccc-11e8-8a9a-b9007ee9f860.png)

I try it in chrome, firefox, opera. All error.

**Comment by pldubouilh** [comment]
You're loading the page as http instead of https, so the serviceworker can't register (SW are https only)
I'll implement a redirection on the webserver :+1:
