### ISSUE TITLE
Can we put just manifest as CLI argument 

### ISSUE THREAD

**Issue by Er-rchydy** [pldubouilh/live-torrent#5]
On localhost it's working fine, i know you specify that in order this to work on website , the website must have HTTPS, you said `the site hosting the videoplayer needs to be served from HTTPS, and serviceworker should be located at the root of the domain. `can you please provide some more information about this, because it's not very clear

**Comment by pldubouilh** [comment]
I just tested locally, and it seems having the chunks and manifest on `http` is ok. 

So say for instance I run the site `live.com`, here's the minimum requirement:
 * I _must_ have https
 * `sw.js`  must exactly be at `https://live.com/sw.js`
 * `bundle.js` can be hosted anywhere, just import it with `<script src="cdn.com/bundle.js"><script>`
 * `hls.js` can be hosted anywhere too, just like `bundle.js`

**Comment by pldubouilh** [comment]
Just thinking - you might also need CORS on your chunks/manifest !

**Comment by Er-rchydy** [comment]
thanks for the explanation
