### ISSUE TITLE
Simple functionality request for didlie.com

### ISSUE THREAD

**Issue by didlie** [pldubouilh/live-torrent#9]
First I invite you to visit didlie.com to see the stable version of the site as a distributed namespace ownership site.

Next I request collaboration to deploy live-torrent to provide anonymous user content to the site in the form of direct p2all webcam feeds using live-torrent.

What didlie needs:
1) A pre-compiled client js script. A script that can be deployed embedded in HTML, dynamically via php.
2) This pre-compiled script must be limited to use via webcam and other peer camera resources.
3) The magnet link generation must be done client side. I can send the links dynamically to the website using AJAX to provide page-specific links... like rooms... where feeds generated in specific name-spaces are displayed in search results.
4) The use of external STUN servers, as a server list, is acceptable, but the goal will to implement a simple STUN server in php on didlie.com, and finally... eventually... to enable a fully peer-reliant web-based or app-based free-floating DidlieDo accross a global network of peers.

--- The bounty on successful collaboration to accomplish these simple code requirements will be allotment of 50 high-level namespaces and developer credit on Didlie.com

**Comment by pldubouilh** [comment]
Not really of interest, sorry
